Added use case 4 and 7 and course entity
CSC207-2022F-UofT/course-project-exam-centre pull request #38
Opened 2022-11-20 02:51 UTC by agentp88

2022-11-21 04:15 UTC, nykoadionisio reviewed
Great work on the code so far! I believe that it follows our CRC model well aside from the slight modifications we discussed in person (which is a good thing!). I do request that we add documentation in the code (JavaDoc) for as many things as you can as it is important we always document our code! Feel free to take a look at my branch (3-use-case-3-register-new-user) for how I wrote out the documentation. Besides that, great work so far!

2022-11-21 12:29 UTC, HarveyRDonnelly requested changes
This is really great work Paul ! As mentioned by Nyko, it's a good idea to write your JavaDoc as you go. That said, I'm happy to merge this and you can create a new issue for JavaDoc to be completed later. I suggest however that the UpdateCourseMembership.java class be renamed to UpdateCourseMembershipInteractor for naming consistency. Moreover, we may need to make some changes to account for the StateTracker but we can discuss this at tutorial later today. Again, really great work !

2022-11-27 21:34 UTC, HarveyRDonnelly commented on src/main/java/entities/Course.java
> +    private final List<TestDoc> tests;
Will be updated as dictionary in later PR

2022-11-27 21:37 UTC, HarveyRDonnelly commented on src/main/java/uc/course/updatemembers/UpdateCMemDsGateway.java
> +    List<String> getCourseEnrollment(String userId);
method name will be updated to getEnrolmentsByUserId for consistency with other use cases

2022-11-27 21:41 UTC, HarveyRDonnelly approved these changes
Great work @agentp88 !! Code is very well written and adheres to the clean architecture. Both use cases are of great quality and documented. Some changes will be needed in a future PR to update the state tracker and make some changes to the course entity

2022-11-27 21:41 UTC, merged